# Настройки сервера
server.port=8080

# Настройки подключения к PostgreSQL
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:6541/ewm}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.datasource.driver-class-name=org.postgresql.Driver

# Настройки Hibernate и SQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Включение отображения SQL-запросов в консоли (для отладки)
spring.jpa.show-sql=true

# Формат дат
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss

# Настройки подключения к серверу статистики
stats-server.url=${STATS_SERVER_URL:http://localhost:9090}